# Generated by Django 2.0 on 2017-12-21 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversation.Graph')),
            ],
        ),
        migrations.AddField(
            model_name='edge',
            name='left_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_edges', to='conversation.Node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='right_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_edges', to='conversation.Node'),
        ),
    ]
