# Generated by Django 2.0 on 2017-12-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='left_node',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='right_node',
        ),
        migrations.RemoveField(
            model_name='node',
            name='graph',
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.DeleteModel(
            name='Graph',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
