# Generated by Django 2.0 on 2018-01-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_chatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='final_message',
            field=models.BooleanField(default=False),
        ),
    ]
