# Generated by Django 2.0 on 2017-12-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='initial_node',
            field=models.BooleanField(default=False),
        ),
    ]
