# Generated by Django 2.0 on 2018-01-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_node_initial_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='final_node',
            field=models.BooleanField(default=False),
        ),
    ]
